-- phpMyAdmin SQL Dump
-- version 3.1.3.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: May 01, 2016 at 10:53 PM
-- Server version: 5.1.33
-- PHP Version: 5.2.9

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `phimanh`
--

-- --------------------------------------------------------

--
-- Table structure for table `binhluan`
--

CREATE TABLE IF NOT EXISTS `binhluan` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hoten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `noidung` longtext COLLATE utf8_unicode_ci,
  `ngaytao` int(11) DEFAULT NULL,
  `duyet` tinyint(4) DEFAULT NULL,
  `id_sanpham` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=9 ;

--
-- Dumping data for table `binhluan`
--

INSERT INTO `binhluan` (`id`, `hoten`, `email`, `noidung`, `ngaytao`, `duyet`, `id_sanpham`) VALUES
(1, '76567', '56756@safa.com', '<p>464545645</p>', 1416641740, 0, 93),
(4, '5765767', 'tanphuong@gmail.com', '45eiotjtioerjtioerjioreio eriotjtiorejtioertioerteio\r\ntjtiorejtiotritj riotri rtir to                                                               ', 1416646688, 1, 93),
(3, '5675', '477575', '<p>7756</p>', NULL, 0, 93),
(6, 'sdgdsgdsg', 'tanphuong20@gmail.com', 'dfdds', 1456673120, 1, 93),
(7, '2535325', '3435@dsf.com', '3533', 1457367261, 0, 93),
(8, '547', 'rfesf@sfdsf.com', '57645', 1461769980, 1, 95);

-- --------------------------------------------------------

--
-- Table structure for table `counter`
--

CREATE TABLE IF NOT EXISTS `counter` (
  `id` int(1) NOT NULL AUTO_INCREMENT,
  `counter` int(10) NOT NULL,
  `DemNgay` int(11) NOT NULL,
  `counter_ngay` int(11) NOT NULL,
  `NgayNgay` date NOT NULL,
  `DemTuan` int(11) NOT NULL,
  `counter_tuan` int(11) NOT NULL,
  `NgayTuan` date NOT NULL,
  `DemThang` int(11) NOT NULL,
  `counter_thang` int(11) NOT NULL,
  `NgayThang` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2 ;

--
-- Dumping data for table `counter`
--

INSERT INTO `counter` (`id`, `counter`, `DemNgay`, `counter_ngay`, `NgayNgay`, `DemTuan`, `counter_tuan`, `NgayTuan`, `DemThang`, `counter_thang`, `NgayThang`) VALUES
(1, 7530, 0, 7530, '2016-01-20', 1, 7530, '2016-01-20', 9, 7529, '2015-12-26');

-- --------------------------------------------------------

--
-- Table structure for table `danhmuc`
--

CREATE TABLE IF NOT EXISTS `danhmuc` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phancap` int(11) DEFAULT NULL,
  `ngaytao` int(11) DEFAULT NULL,
  `duyet` tinyint(4) DEFAULT NULL,
  `sapxep` int(11) DEFAULT NULL,
  `taotrang` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=5 ;

--
-- Dumping data for table `danhmuc`
--

INSERT INTO `danhmuc` (`id`, `ten`, `phancap`, `ngaytao`, `duyet`, `sapxep`, `taotrang`) VALUES
(1, 'Trang chủ', 0, 1415805745, 1, 1, 1),
(2, 'Phim mới', 0, 1456848652, 1, 2, 2),
(3, 'Thể loại', 0, 1456848669, 1, 3, 2),
(4, 'Quốc gia', 0, 1456848678, 1, 4, 2);

-- --------------------------------------------------------

--
-- Table structure for table `hinhanh`
--

CREATE TABLE IF NOT EXISTS `hinhanh` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ngaytao` int(11) DEFAULT NULL,
  `sapxep` int(11) DEFAULT NULL,
  `hinhanh` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `duyet` tinyint(4) DEFAULT NULL,
  `vitri` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=8 ;

--
-- Dumping data for table `hinhanh`
--

INSERT INTO `hinhanh` (`id`, `ten`, `ngaytao`, `sapxep`, `hinhanh`, `duyet`, `vitri`) VALUES
(6, 'Banner', 1456675528, 0, '1456675528.jpg', 1, 1),
(7, 'Logo', 1456675793, 0, '', 1, 3);

-- --------------------------------------------------------

--
-- Table structure for table `nhom`
--

CREATE TABLE IF NOT EXISTS `nhom` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ngaytao` int(11) DEFAULT NULL,
  `duyet` tinyint(4) DEFAULT NULL,
  `sapxep` int(11) DEFAULT NULL,
  `quyentruycap` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=10 ;

--
-- Dumping data for table `nhom`
--

INSERT INTO `nhom` (`id`, `ten`, `ngaytao`, `duyet`, `sapxep`, `quyentruycap`) VALUES
(1, 'Admin', 1457366510, 1, 1, 0),
(7, 'Khách', 1457145459, 1, 12, 2);

-- --------------------------------------------------------

--
-- Table structure for table `sanpham`
--

CREATE TABLE IF NOT EXISTS `sanpham` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hinhanh` longtext COLLATE utf8_unicode_ci,
  `ngaytao` int(11) DEFAULT NULL,
  `sapxep` int(11) DEFAULT NULL,
  `duyet` tinyint(4) DEFAULT NULL,
  `thongtin` longtext COLLATE utf8_unicode_ci,
  `noidung` longtext COLLATE utf8_unicode_ci,
  `id_danhmuc` int(11) DEFAULT NULL,
  `lanxem` int(11) DEFAULT '0',
  `lan_chon` int(11) DEFAULT '0',
  `diem_chon` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=136 ;

--
-- Dumping data for table `sanpham`
--

INSERT INTO `sanpham` (`id`, `ten`, `hinhanh`, `ngaytao`, `sapxep`, `duyet`, `thongtin`, `noidung`, `id_danhmuc`, `lanxem`, `lan_chon`, `diem_chon`) VALUES
(87, 'Phim hành động', 'phim.jpg', 1421059447, 1, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(86, 'Phim hành động', 'phim.jpg', 1421092815, 1, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(89, 'Phim hành động', 'phim.jpg', 1421087771, 4, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(88, 'Phim hành động', 'phim.jpg', 1421059577, 2, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(90, 'Phim hành động', 'phim.jpg', 1421059949, 3, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(91, 'Phim hành động', 'phim.jpg', 1421059966, 5, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(92, 'Phim hành động', '["01462112995.jpg","11462112995.jpg"]', 1462112995, 0, 1, '<p>H&atilde;ng sản xuất: Mỹ  Thể loại: H&agrave;nh động  Đạo diễn : Ch&acirc;u Tinh Tr&igrave;  Năm ph&aacute;t h&agrave;nh  : 2015  Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</p>', '<p>Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.  Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y tai nạn.</p>', 2, 9, 1, 5),
(93, 'Phim hành động', 'phim.jpg', 1456850711, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 28, 7, 25),
(94, 'Phim hành động', 'phim.jpg', 1421060023, 11, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(95, 'Phim hành động', 'phim.jpg', 1421061966, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 33, 7, 26),
(96, 'Phim hành động', 'phim.jpg', 1421062053, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(97, 'Phim hành động', 'phim.jpg', 1421063494, 13, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(98, 'Phim hành động', 'phim.jpg', 1421063509, 12, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(99, 'Phim hành động', 'phim.jpg', 1421063592, 14, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(100, 'Phim hành động', 'phim.jpg', 1421064266, 16, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(101, 'Phim hành động', 'phim.jpg', 1421071933, 17, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(102, 'Phim hành động', 'phim.jpg', 1421089699, 19, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(104, 'Phim hành động', 'phim.jpg', 1421074017, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(105, 'Phim hành động', 'phim.jpg', 1421074339, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 5, 1, 5),
(106, 'Phim hành động', 'phim.jpg', 1421074553, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(108, 'Phim hành động', 'phim.jpg', 1421075449, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(110, 'Phim hành động', 'phim.jpg', 1421075916, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(111, 'Phim hành động', 'phim.jpg', 1421076094, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 5, 0, 0),
(112, 'Phim hành động', 'phim.jpg', 1421076962, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(113, 'Phim hành động', 'phim.jpg', 1421077999, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(114, 'Phim hành động', 'phim.jpg', 1421085132, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(115, 'Phim hành động', 'phim.jpg', 1421085482, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(116, 'Phim hành động', 'phim.jpg', 1421085700, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0);
INSERT INTO `sanpham` (`id`, `ten`, `hinhanh`, `ngaytao`, `sapxep`, `duyet`, `thongtin`, `noidung`, `id_danhmuc`, `lanxem`, `lan_chon`, `diem_chon`) VALUES
(117, 'Heo hai lát hộp', 'phim.jpg', 1421085875, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(118, 'Phim hành động', 'phim.jpg', 1421086066, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(119, 'Phim hành động', 'phim.jpg', 1421087162, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(120, 'Phim hành động', 'phim.jpg', 1421087379, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(121, 'Phim hành động', 'phim.jpg', 1421087674, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(122, 'Phim hành động', 'phim.jpg', 1421088171, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(123, 'Phim hành động', 'phim.jpg', 1421088927, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(124, 'Phim hành động', 'phim.jpg', 1421089637, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(125, 'Phim hành động', 'phim.jpg', 1421089907, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(126, 'Phim hành động', 'phim.jpg', 1421090149, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(127, 'Phim hành động', 'phim.jpg', 1421090416, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(128, 'Phim hành động', 'phim.jpg', 1421090662, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(129, 'Phim hành động', 'phim.jpg', 1421090788, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(130, 'Phim hành động', 'phim.jpg', 1421091233, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(131, 'Phim hành động', 'phim.jpg', 1421091459, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(132, 'Phim hành động', 'phim.jpg', 1421092065, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(133, 'Phim hành động', 'phim.jpg', 1421092706, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(134, 'Phim hành động', 'phim.jpg', 1421093041, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0),
(135, 'Phim hành động', 'phim.jpg', 1421093453, 0, 1, '<p><span style="font-size: small;"><span style="color: #000000;">H&atilde;ng sản xuất</span><a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/unilever">:<span style="color: #000000;"> M</span></a>ỹ</span></p>\r\n<p><span style="color: #000000; font-size: small;">Thể loại: H&agrave;nh động<a class="text_link" style="font-family: Arial,sans-serif; color: #0e76bc; text-decoration: none;" href="http://www.vatgia.com/s/vi%E1%BB%87t+nam"><br /></a></span></p>\r\n<p><span style="color: #000000; font-size: small;">Đạo diễn : Ch&acirc;u Tinh Tr&igrave;</span></p>\r\n<p><span style="color: #000000; font-size: small;">Năm ph&aacute;t h&agrave;nh &nbsp;: 2015</span></p>\r\n<p><span style="color: #000000; font-size: small;">Nội dung t&oacute;m tắt : Phim dựa tr&ecirc;n kịch bản h&agrave;nh động v&agrave; h&agrave;i hước</span></p>', '<p class="Normal">Chiều 1/3, thượng t&aacute; Nguyễn Viết Chức, Ph&oacute; trưởng C&ocirc;ng an quận Long  Bi&ecirc;n (H&agrave; Nội) cho biết, ngo&agrave;i c&ocirc;ng an quận, th&agrave;nh phố, Cục Cảnh s&aacute;t giao  th&ocirc;ng (Bộ C&ocirc;ng an), Viện kiểm s&aacute;t cũng tham gia điều tra vụ tai nạn  giao th&ocirc;ng đặc biệt nghi&ecirc;m trọng ở phố &Aacute;i Mộ.</p>\r\n<p class="Normal">Sau khi thu thập chứng cứ, lời khai của người li&ecirc;n quan, kh&aacute;m nghiệm  hiện trường, đặc biệt lấy dấu v&acirc;n tay tr&ecirc;n v&ocirc; lăng, c&ocirc;ng an khẳng định  Nguyễn Quang Vinh (39 tuổi, ở Thượng Thanh, Long Bi&ecirc;n) l&aacute;i xe Camry g&acirc;y  tai nạn.</p>', 2, 0, 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `sothich`
--

CREATE TABLE IF NOT EXISTS `sothich` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ten` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sapxep` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=10 ;

--
-- Dumping data for table `sothich`
--

INSERT INTO `sothich` (`id`, `ten`, `sapxep`) VALUES
(1, 'Bóng Bàn', 1),
(2, 'Cầu Lông', 2),
(3, 'Bơi Lội', 3),
(4, 'Điền Kinh', 4),
(5, 'Bóng Đá', 6),
(6, 'Bi Lắc', 7),
(7, 'Bi Da', 8),
(8, 'Cờ Tướng', 9),
(9, 'Cờ Vua', 5);

-- --------------------------------------------------------

--
-- Table structure for table `thanhvien`
--

CREATE TABLE IF NOT EXISTS `thanhvien` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `hoten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `dienthoai` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `diachi` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `duyet` tinyint(4) DEFAULT NULL,
  `id_nhom` int(11) DEFAULT NULL,
  `sapxep` int(11) DEFAULT NULL,
  `ngaysinh` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `gioitinh` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=70 ;

--
-- Dumping data for table `thanhvien`
--

INSERT INTO `thanhvien` (`id`, `username`, `hoten`, `dienthoai`, `diachi`, `email`, `password`, `duyet`, `id_nhom`, `sapxep`, `ngaysinh`, `gioitinh`) VALUES
(57, 'admin', '1saf', 'sdfds', 'hcm', 'tanphuong20@gmail.com', '123456', 1, 1, 1, '08-03-2016', 'nam'),
(59, 'khachhang', 'sfdf', 'fsdfdsfsf', 'fdfsf', 'fsfsdff', '123', 1, 7, 1, NULL, NULL),
(61, 'cuong', 'nguyen manh cuong', '097736226', 'binh duong', 'vanminh@gmail.com', '123', 1, 7, 3, NULL, NULL),
(69, '436436', '4365', '1', '1', '232@wd.com', '1', 1, 7, 0, '14-03-2016', 'nam');

-- --------------------------------------------------------

--
-- Table structure for table `thanhvien_sothich`
--

CREATE TABLE IF NOT EXISTS `thanhvien_sothich` (
  `id_thanhvien` int(11) DEFAULT NULL,
  `id_sothich` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `thanhvien_sothich`
--

INSERT INTO `thanhvien_sothich` (`id_thanhvien`, `id_sothich`) VALUES
(69, 9),
(69, 1),
(57, 5),
(57, 1);

-- --------------------------------------------------------

--
-- Table structure for table `thongtin`
--

CREATE TABLE IF NOT EXISTS `thongtin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ten` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `noidung` longtext COLLATE utf8_unicode_ci,
  `loai` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=4 ;

--
-- Dumping data for table `thongtin`
--

INSERT INTO `thongtin` (`id`, `ten`, `noidung`, `loai`) VALUES
(1, 'Footer', '<p><span style="color: #ff0000; font-weight: bold;">C&ocirc;ng ty TNHH Sản xuất phim</span><br /> Địa chỉ : 451 B&ugrave;i Ngọc Thu, Th&agrave;nh phố Thủ Dầu Một, Quảng B&igrave;nh<br /> Điện thoại : 0935545767</p>', 'footer');

-- --------------------------------------------------------

--
-- Table structure for table `users_online`
--

CREATE TABLE IF NOT EXISTS `users_online` (
  `visitor` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `lastvisit` int(14) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `users_online`
--

INSERT INTO `users_online` (`visitor`, `lastvisit`) VALUES
('127.0.0.1', 1462114022);
